// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMqtoOFMvXrPymuBixzUcIyYomXW3dgE',
    appId: '1:994815950130:web:0421a521f6cedfd91ceb2b',
    messagingSenderId: '994815950130',
    projectId: 'anas-579a6',
    authDomain: 'anas-579a6.firebaseapp.com',
    storageBucket: 'anas-579a6.firebasestorage.app',
    measurementId: 'G-S7B3ZWPNWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqrwAV7SgFY1dEiKEc0JpnscYQstNCt1Q',
    appId: '1:994815950130:android:f657d1855fb668fc1ceb2b',
    messagingSenderId: '994815950130',
    projectId: 'anas-579a6',
    storageBucket: 'anas-579a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_nWTRKvV17M-Vi_cgDi3PbriojxR_X4',
    appId: '1:994815950130:ios:450e9b1fb872ad6b1ceb2b',
    messagingSenderId: '994815950130',
    projectId: 'anas-579a6',
    storageBucket: 'anas-579a6.firebasestorage.app',
    iosBundleId: 'com.example.travelApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_nWTRKvV17M-Vi_cgDi3PbriojxR_X4',
    appId: '1:994815950130:ios:450e9b1fb872ad6b1ceb2b',
    messagingSenderId: '994815950130',
    projectId: 'anas-579a6',
    storageBucket: 'anas-579a6.firebasestorage.app',
    iosBundleId: 'com.example.travelApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeMqtoOFMvXrPymuBixzUcIyYomXW3dgE',
    appId: '1:994815950130:web:76ad9a7f2f2fae051ceb2b',
    messagingSenderId: '994815950130',
    projectId: 'anas-579a6',
    authDomain: 'anas-579a6.firebaseapp.com',
    storageBucket: 'anas-579a6.firebasestorage.app',
    measurementId: 'G-6KQLVEPTG5',
  );
}
